### ISSUE TITLE
How to use FSDP if some parameters are moving average of other parameters

### ISSUE THREAD

**Issue by amsword** [facebookresearch/fairscale#805] opened 2021-09-20 00:09 UTC
## ❓ Questions and Help

The following program crashes with the following messages. Any suggestion on how to use FSDP to update parameters by moving average?

```shell
~/code/quickdetection/scripts/run.py in forward(self, x)
  10652             n2p = dict(self.named_parameters())
  10653             for n, p in self.teacher.named_parameters():
> 10654                 p.data = p * 0.999 + n2p[n].data * (1. - 0.999)
  10655         x2 = self.teacher.forward_payload(x)
  10656         return (x1 * x1).sum() * 0.5 + ((x1 - x2) ** 2).sum()

KeyError: '_fsdp_wrapped_module.flat_param'
*** NameError: name 'pdb' is not defined
> /home/jianfw/code/quickdetection/scripts/run.py(10654)forward()
  10652             n2p = dict(self.named_parameters())
  10653             for n, p in self.teacher.named_parameters():
> 10654                 p.data = p * 0.999 + n2p[n].data * (1. - 0.999)
  10655         x2 = self.teacher.forward_payload(x)
  10656         return (x1 * x1).sum() * 0.5 + ((x1 - x2) ** 2).sum()
```

```python
  class L2MomentumTeacher(nn.Module):
      def __init__(self):
          super().__init__()
          for i in range(200):
              setattr(self, 'layer_{}'.format(i), nn.Linear(1024, 1024))
          self.teacher = copy.deepcopy(self)

      def forward_payload(self, x):
          for i in range(200):
              l = getattr(self, 'layer_{}'.format(i))
              x = l(x)
          return x

      def forward(self, x):
          x1 = self.forward_payload(x)

          with torch.no_grad():
              n2p = dict(self.named_parameters())
              for n, p in self.teacher.named_parameters():
                  p.data = p * 0.999 + n2p[n].data * (1. - 0.999)
          x2 = self.teacher.forward_payload(x)
          return (x1 * x1).sum() * 0.5 + ((x1 - x2) ** 2).sum()

  def test_fsdp3():
      ensure_init_process_group(port=12445)
      from fairscale.nn.data_parallel import FullyShardedDataParallel as FSDP
      fsdp_params = dict(wrapper_cls=FSDP,
                         mixed_precision=True,
                         flatten_parameters=True,
                         reshard_after_forward=True,
                         )
      from fairscale.nn.wrap import auto_wrap, enable_wrap, wrap
      model = L2MomentumTeacher().cuda()
      with enable_wrap(**fsdp_params):
          model = auto_wrap(model)
          if not isinstance(model, FSDP):
              model = wrap(model)
      for _ in range(10):
          data = torch.zeros((1, 1024)).cuda()
          y = model(data)
          import ipdb;ipdb.set_trace(context=15)
          y.backward()
          # optimizer/scheduler update

```

**Comment by anj-s** [comment] 2021-09-20 15:59
Given we flatten params, there might be a mismatch when you use named_parameters. Can you try this with flatten_parameters=False instead of flatten_parameters=True?

**Comment by amsword** [comment] 2021-09-20 16:43
> Given we flatten params, there might be a mismatch when you use named_parameters. Can you try this with flatten_parameters=False instead of flatten_parameters=True?

Thanks for the suggestion. I tried, but it fails with the following error.
```shell
~/code/quickdetection/scripts/run.py in forward(self, x)
  10793             n2p = dict(self.named_parameters())
  10794             for n, p in self.teacher.named_parameters():
> 10795                 p.data = p * 0.999 + n2p[n].data * (1. - 0.999)
  10796         x2 = self.teacher.forward_payload(x)
  10797         return (x1 * x1).sum() * 0.5 + ((x1 - x2) ** 2).sum()

KeyError: '_fsdp_wrapped_module.layer_0.weight'
*** NameError: name 'pdb' is not defined
> /home/jianfw/code/quickdetection/scripts/run.py(10795)forward()
  10793             n2p = dict(self.named_parameters())
  10794             for n, p in self.teacher.named_parameters():
> 10795                 p.data = p * 0.999 + n2p[n].data * (1. - 0.999)
  10796         x2 = self.teacher.forward_payload(x)
  10797         return (x1 * x1).sum() * 0.5 + ((x1 - x2) ** 2).sum()
```

Then, do you think it is ok to remove the special keyword of _fsdp_wrapped_module to update the parameters? Some concern is that each rank only has partial valid parameters based on how FSDP works. Does this update gather the correct parameters?

```python
  class L2MomentumTeacher(nn.Module):
      def __init__(self):
          super().__init__()
          for i in range(200):
              setattr(self, 'layer_{}'.format(i), nn.Linear(1024, 1024))
          self.teacher = copy.deepcopy(self)

      def forward_payload(self, x):
          for i in range(200):
              l = getattr(self, 'layer_{}'.format(i))
              x = l(x)
          return x

      def forward(self, x):
          x1 = self.forward_payload(x)

          with torch.no_grad():
              n2p = dict(self.named_parameters())
              # remove _fsdp_wrapped_module
              n2p = dict([(n.replace('_fsdp_wrapped_module.', ''), p) for n, p in
                    n2p.items()])
              for n, p in self.teacher.named_parameters():
                  n = n.replace('_fsdp_wrapped_module.', '')
                  p.data = p * 0.999 + n2p[n].data * (1. - 0.999)
          x2 = self.teacher.forward_payload(x)
          return (x1 * x1).sum() * 0.5 + ((x1 - x2) ** 2).sum()

  def test_fsdp3():
      ensure_init_process_group(port=12445)
      from fairscale.nn.data_parallel import FullyShardedDataParallel as FSDP
      fsdp_params = dict(wrapper_cls=FSDP,
                         mixed_precision=True,
                         flatten_parameters=False,
                         reshard_after_forward=True,
                         )
      from fairscale.nn.wrap import auto_wrap, enable_wrap, wrap
      model = L2MomentumTeacher().cuda()
      with enable_wrap(**fsdp_params):
          model = auto_wrap(model)
          if not isinstance(model, FSDP):
              model = wrap(model)
      for _ in range(10):
          data = torch.zeros((1, 1024)).cuda()
          with torch.cuda.amp.autocast(enabled=True):
              y = model(data)
          y.backward()
          # optimizer/scheduler update
```
The parameter updates is good to go, but it fails with the following. Pytorch version = 1.7.1. fairscale version = 0.3.7.
```shell
~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    219                 retain_graph=retain_graph,
    220                 create_graph=create_graph)
--> 221         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    222
    223     def register_hook(self, hook):

~/anaconda3/envs/py37/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133
    134

SystemError: <built-in method run_backward of torch._C._EngineBase object at 0x7efdd8d5dfd0> returned NULL without setting an error
*** NameError: name 'pdb' is not defined
> /home/jianfw/anaconda3/envs/py37/lib/python3.7/site-packages/torch/autograd/__init__.py(132)backward()
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133
    134
```

**Comment by min-xu-ai** [comment] 2021-09-20 23:56
Thanks @anj-s for the suggestion.

I think the issue is that self.teacher is likely wrapped by FSDP. @amsword, can you print out the entire model and paste the output here? Just auto_wrap a model with FSDP may not give you the best effect on memory saving and it can cause the error like what you are seeing because you cannot always reach into a FSDP-wrapped module like it is before it is wrapped.

@zhaojuanmao @mrshenli

**Comment by amsword** [comment] 2021-09-21 04:14
Thanks @min-xu-ai @anj-s . The error disappears after freezing the parameters in self.teacher. So now, it is runnable, but is it working as expected as each rank only holds a portion of the parameters? If logically it is correct, in this way, it has no speed-up compared with the traditional pytorch/DDP, right?

**Comment by min-xu-ai** [comment] 2021-09-21 05:46
FSDP is not primarily for speeding up training compared to DDP. It is mainly for training bigger models. Also, you will need to wrap your big model in careful ways to fully realize its potential.

**Comment by anj-s** [comment] 2021-10-15 13:43
Closing this issue for now. Please reopen or file a new issue if you have questions. Thanks!

**Closed by anj-s** 2021-10-15 13:43 UTC
