### ISSUE TITLE
Got error messages at 0a526bcbe212b043a00a5bdfae73c7ef532c88b4

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#904] opened 2022-01-08 09:37 UTC
Hi, I wrapped my model with FSDP, and the training process worked fine until I updated the fairscale to 0a526bcbe212b043a00a5bdfae73c7ef532c88b4. I got the following error messages, and it seemed that the problem was from backward. Could you tell me where the problem came from?
```
 File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1621, in _post_backward_hook
    self._reducer.reduce_scatter_async(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/fairscale/utils/reduce_scatter_bucketer.py", line 131, in reduce_scatter_async
    assert (
AssertionError: reduce_scatter received 2 inputs, expected group.size() (8)
```

**Comment by anj-s** [comment] 2022-01-08 17:38
@foreveronehundred  thank you for reporting this issue! As a temporary fix can you pass `ProcessGroupName.default` to the `process_group_reduce_scatter ` API parameter?  

Can you provide a small repro since we are not seeing any failures in our tests. Wondering if it is something specific to your model/training loop.

cc @tmarkstrum

**Comment by tmarkstrum** [comment] 2022-01-10 20:42
@foreveronehundred I could not reproduce the error. What is your FSDP config/parameter? Did you create "process_group" in advance, and pass in  "process_group" as the FSDP API parameter?

**Comment by foreveronehundred** [comment] 2022-01-11 01:57
> u for reporting this issue! As a temporary fix can you pass `ProcessGroupName.default` to the `process_group_reduce_scatter ` API parameter?
I will first try this and tell you if it works.

**Comment by foreveronehundred** [comment] 2022-01-11 02:05
> @foreveronehundred thank you for reporting this issue! As a temporary fix can you pass `ProcessGroupName.default` to the `process_group_reduce_scatter ` API parameter?
> 
> Can you provide a small repro since we are not seeing any failures in our tests. Wondering if it is something specific to your model/training loop.
> 
> cc @tmarkstrum

I will first try this and tell you if it works.

**Comment by tmarkstrum** [comment] 2022-01-13 17:49
@foreveronehundred could you please check out the latest code in main? Please let me know if the issue still exists. If passing ProcessGroupName.default works, please let me know. Then I can close this issue.

**Comment by foreveronehundred** [comment] 2022-01-14 01:52
> @foreveronehundred could you please check out the latest code in main? Please let me know if the issue still exists. If passing ProcessGroupName.default works, please let me know. Then I can close this issue.

The problem has been solved in the latest branch. Please close the issue. Thanks.

**Closed** 2022-01-18 05:13 UTC
Labels: FSDP
