### ISSUE TITLE
[bug] pip package 0.1.3 fails to install

### ISSUE THREAD

**Issue by leezu** [facebookresearch/fairscale#294] opened 2021-01-07 16:56 UTC
Both `python3.8 -m pip install fairscale --verbose` and `python3.8 -m pip install fairscale --no-build-isolation --verbose` trigger

```
ninja: error: '/tmp/pip-install-zqe21k7a/fairscale_4066f1fa225242299ead5fd852fd2ce8/fairscale/clib/fused_adam_cuda/fused_adam_cuda.cpp', needed by '/t
mp/pip-install-zqe21k7a/fairscale_4066f1fa225242299ead5fd852fd2ce8/build/temp.linux-x86_64-3.8/fairscale/clib/fused_adam_cuda/fused_adam_cuda.o', missin
g and no known rule to make it
```

Cloning the repository and running `python3.8 -m pip install . --verbose` from within the directory works fine.

**Comment by blefaudeux** [comment] 2021-01-07 17:22
oh, I was the one doing this release, I may have done something wrong. Testing locally I cannot reproduce though, @msbaines  would you have an idea ? I remember seeing this issue discussed before

**Comment by blefaudeux** [comment] 2021-01-07 17:24
Maybe related to https://github.com/facebookresearch/fairscale/issues/190

**Comment by blefaudeux** [comment] 2021-01-07 17:31
ok, I just checked the package and these files are missing indeed, I'm not sure why the pip install works out for me, maybe because of caching. Trying to publish a new package asap

**Comment by leezu** [comment] 2021-01-07 17:54
Thank you. Maybe you tested on a machine without cuda? In that case the installer will skip compiling the files

**Comment by blefaudeux** [comment] 2021-01-07 17:55
> Thank you. Maybe you tested on a machine without cuda? In that case the installer will skip compiling the files

I was writing just that, message almost crossed. I'm testing on a machine which has cuda of course, but just the runtime, not the toolkit, and in that case the cu files are skipped indeed

**Comment by blefaudeux** [comment] 2021-01-07 18:00
@leezu would you mind testing please ?
[fairscale-0.1.4.tar.gz](https://github.com/facebookresearch/fairscale/files/5783203/fairscale-0.1.4.tar.gz)

**Comment by blefaudeux** [comment] 2021-01-07 18:57
closed automatically, sorry about that, waiting for a confirmation from @leezu that the latest pip package works

**Comment by msbaines** [comment] 2021-01-07 19:02
This should have been fixed by #221. Were you using an older version of pip?

**Comment by blefaudeux** [comment] 2021-01-07 19:25
> This should have been fixed by #221. Were you using an older version of pip?

if it's a question for me, I'm not sure, could be. The package was definitely missing the cuda files, should be fixed by now

**Comment by leezu** [comment] 2021-01-07 20:36
Thank you @blefaudeux. `python3.8 -m pip install --verbosehttps://github.com/facebookresearch/fairscale/files/5783203/fairscale-0.1.4.tar.gz` works fine.

**Comment by blefaudeux** [comment] 2021-01-07 20:49
Thank you @leezu, and sorry for the mistake in the first place. Closing the issue

**Closed by blefaudeux** 2021-01-07 20:49 UTC
Labels: bug
